name: learn-github-actions
run-name: Learn GitHub Actions

on:
  push:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, GitHub Actions!"
            # add a step that is able to connect to a server using ssh
            - name: SSH to Server
              uses: appleboy/ssh-action@v1.2.4
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                script: |
                  echo "Connected to the server successfully!"
                  uname -a
            